### ISSUE TITLE
docker compose errors

### ISSUE THREAD

**Issue by bigos** [ultralisp/ultralisp#200]

**Comment by bigos** [comment]
I was trying to install docker and configure DNS as in this link: https://github.com/bigos/ultralisp-notes/blob/main/docker-install-and-config.org.

also this time the same version of docker-compose was not installed from apt but from pip,

When I try to run docker-compose run --rm mito migrate
I get this error:
```

$ docker-compose run --rm mito migrate
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused



```

**Comment by bigos** [comment]
Is it possible that the documentation is wrong?

https://phase2.github.io/devtools/getting-started/linux-installation/#linux-installation-on-ubuntulinux-mintdebian
