### ISSUE TITLE
Project not added

### ISSUE THREAD

**Issue by simendsjo** [ultralisp/ultralisp#252]
I tried adding the following repo a week ago, but it looks like there was an internal error (process timeout), and tæit won't progress any further. https://ultralisp.org/projects/simendsjo/sijo-doctest

The check button is grayed out, but I can press it and get a 200. But it doesn't look like it's put in any queue though. I cannot see it on the home page, and just waiting doesn't seem to update anything.

```
Traceback (most recent call last):
   0 File "/app/src/rpc/core.lisp"
       In (FLET "FUN26" :IN ULTRALISP/RPC/CORE:SUBMIT-TASK)
     Args (#<unused argument>)
   1 File "/app/src/rpc/core.lisp", line 95
       In ULTRALISP/RPC/CORE:SUBMIT-TASK
     Args (ULTRALISP/PIPELINE/CHECKING::PERFORM2 :LISP-IMPLEMENTATION :SBCL :ARGS (#<ULTRALISP/MODELS/CHECK:CHECK2 PENDING ADDED-PROJECT for #<SOURCE github://simendsjo/sijo-doctest@NIL (v0)>>) :TIMEOUT 900)
   2 File "/app/src/pipeline/checking.lisp"
       In (FLET "CONNECTED-FUNC1" :IN ULTRALISP/PIPELINE/CHECKING:PERFORM-REMOTELY)
     Args ()
   3 File "/app/src/db.lisp", line 100
       In ULTRALISP/DB::CALL-WITH-TRANSACTION
     Args (#<FUNCTION (FLET "CONNECTED-FUNC1" :IN ULTRALISP/PIPELINE/CHECKING:PERFORM-REMOTELY) {7F57E350D93B}>)
   4 File "/app/src/db.lisp", line 126
       In ULTRALISP/DB::CALL-WITH-CONNECTION
     Args (#<FUNCTION (FLET "CONNECTED-FUNC1" :IN ULTRALISP/PIPELINE/CHECKING:PERFORM-REMOTELY) {7F57E350D93B}> :CACHED NIL)
   5 File "/app/src/pipeline/checking.lisp"
       In (LAMBDA () :IN ULTRALISP/PIPELINE/CHECKING:PERFORM-REMOTELY)
     Args ()
   6 File "/app/src/pipeline/checking.lisp", line 100
       In ULTRALISP/PIPELINE/CHECKING:PERFORM-REMOTELY
     Args (#<ULTRALISP/MODELS/CHECK:CHECK2 PENDING ADDED-PROJECT for #<SOURCE github://simendsjo/sijo-doctest@NIL (v0)>> :FORCE NIL)
   7 File "/app/src/pipeline/checking.lisp"
       In (FLET ULTRALISP/PIPELINE/CHECKING:PERFORM :IN ULTRALISP/PIPELINE/CHECKING:PERFORM-PENDING-CHECKS)
     Args (#<ULTRALISP/MODELS/CHECK:CHECK2 PENDING ADDED-PROJECT for #<SOURCE github://simendsjo/sijo-doctest@NIL (v0)>>)
   8 File "/app/src/pipeline/checking.lisp"
       In (FLET "FORM-FUN-23" :IN ULTRALISP/PIPELINE/CHECKING:PERFORM-PENDING-CHECKS)
     Args ()
   9 File "/app/src/pipeline/checking.lisp", line 159
       In ULTRALISP/PIPELINE/CHECKING:PERFORM-PENDING-CHECKS
     Args (:FORCE NIL :LISP-IMPLEMENTATION :SBCL)
  10 File "/app/src/cron.lisp"
       In (FLET "CONNECTED-FUNC9" :IN ULTRALISP/CRON::PERFORM-CHECKS)
     Args ()
  11 File "/app/src/db.lisp", line 100
       In ULTRALISP/DB::CALL-WITH-TRANSACTION
     Args (#<FUNCTION (FLET "CONNECTED-FUNC9" :IN ULTRALISP/CRON::PERFORM-CHECKS) {5260AC1B}>)
  12 File "/app/src/db.lisp", line 126
       In ULTRALISP/DB::CALL-WITH-CONNECTION
     Args (#<FUNCTION (FLET "CONNECTED-FUNC9" :IN ULTRALISP/CRON::PERFORM-CHECKS) {5260AC1B}>)
  13 File "/app/src/cron.lisp"
       In (FLET "FORM-FUN-8" :IN ULTRALISP/CRON::PERFORM-CHECKS)
     Args ()
  14 File "/app/src/cron.lisp"
       In (LAMBDA () :IN ULTRALISP/CRON::PERFORM-CHECKS)
     Args ()
  15 File "/app/src/cron.lisp", line 96
       In ULTRALISP/CRON::PERFORM-CHECKS
     Args ()
  16 File "/app/.qlot/dists/ultralisp/software/sionescu-bordeaux-threads-20230921222339/apiv1/bordeaux-threads.lisp"
       In (LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-S…
     Args ()
  17 File "unknown"
       In (FLET SB-UNIX::BODY :IN SB-THREAD::RUN)
     Args ()
  18 File "unknown"
       In (FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN)
     Args ()
  19 File "unknown"
       In (FLET SB-UNIX::BODY :IN SB-THREAD::RUN)
     Args ()
  20 File "unknown"
       In (FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN)
     Args ()
  21 File "unknown"
       In SB-THREAD::RUN
     Args ()
  22 File "unknown"
       In "foreign function: call_into_lisp"
     Args ()
  23 File "unknown"
       In "foreign function: funcall1"
     Args ()
Condition COM.METABANG.TRIVIAL-TIMEOUT:TIMEOUT-ERROR: Process timeout
```

**Comment by svetlyak40wt** [comment]
The problem is that this project is not included into any dsitribution:

<img width="740" alt="Screenshot 2024-03-08 at 19 12 20" src="https://github.com/ultralisp/ultralisp/assets/24827/0ee9277c-fffe-479e-bf4a-ba2741806c3a">

Add it to some distribution.

**Comment by svetlyak40wt** [comment]
It would be nice to make this enchancement:

https://github.com/ultralisp/ultralisp/issues/253
