### ISSUE TITLE
Corrupt NEXT-chain in #<HASH-TABLE :TEST EQ :COUNT 32 {1002027B13}>

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#74]
```
Traceback (most recent call last):
  File "NIL", line NIL, in SIGNAL-CO…
    (SB-IMPL::SIGNAL-CORRUPT-HASH-TABLE-BUCKET
     #<HASH-TABLE :TEST EQ :COUNT 32 {1002027B13}>)
  File "NIL", line NIL, in GETHASH/E…
    (SB-IMPL::GETHASH/EQ #<unavailable argument> #<unavailable argument>
                         #<unavailable argument>)
  File "/app/.qlot/dists/cl-dbi/software/cl-dbi-49-fix-manual-commit/src/dbi.lisp", line 108, in GET-CONNE…
    (DBI::GET-CONNECTION-POOL)
  File "/app/.qlot/dists/cl-dbi/software/cl-dbi-49-fix-manual-commit/src/dbi.lisp", line 113, in CONNECT-C…
    (DBI:CONNECT-CACHED :POSTGRES :HOST "172.17.0.1" :DATABASE-NAME "ultralisp"
                        :USERNAME "ultralisp" :PASSWORD "Buet7oadD8ar")
  File "/app/src/db.lisp", line 50, in CONNECT
    (ULTRALISP/DB::CONNECT :HOST NIL :DATABASE-NAME NIL :USERNAME NIL :PASSWORD
                           NIL :CACHED T)
  File "/app/src/cron.lisp", line 67, in PERFORM-C…
    (ULTRALISP/CRON::PERFORM-CHECKS)
  File "/app/.qlot/dists/ultralisp/software/sionescu-bordeaux-threads-20200116181619/src/bordeaux-threads.lisp", line NIL, in (LAMBDA (…
    ((LAMBDA () :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
  File "NIL", line NIL, in (FLET BOD…
    ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
  File "NIL", line NIL, in (FLET WIT…
    ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
  File "NIL", line NIL, in (FLET WIT…
    ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))


Condition: Corrupt NEXT-chain in #<HASH-TABLE :TEST EQ :COUNT 32 {1002027B13}>. This is probably caused by multiple threads accessing the same hash-table without locking.
```

**Comment by svetlyak40wt** [comment]
Also, probably this error which happens from time to time also related to the cached connections:

```
Traceback (most recent call last):
  File "NIL", line NIL, in BUG
    (SB-INT:BUG "~@<failed AVER: ~2I~_~S~:>"
                (= (HASH-TABLE-COUNT SB-IMPL::TABLE) SB-IMPL::HWM))
  File "NIL", line NIL, in FAILED-AV…
    ("FAILED-AVER-ERROR" (= (HASH-TABLE-COUNT SB-IMPL::TABLE) SB-IMPL::HWM))
  File "NIL", line NIL, in INTERNAL-…
    (SB-KERNEL:INTERNAL-ERROR #.(SB-SYS:INT-SAP #X7F59ACE1DC80)
                              #<unused argument>)
  File "NIL", line NIL, in foreign f…
    ("foreign function: call_into_lisp")
  File "NIL", line NIL, in foreign f…
    ("foreign function: funcall2")
  File "NIL", line NIL, in foreign f…
    ("foreign function: handle_trap")
  File "NIL", line NIL, in foreign f…
    ("foreign function: #x419B5E")
  File "NIL", line NIL, in GROW-HASH…
    (SB-IMPL::GROW-HASH-TABLE #<HASH-TABLE :TEST EQ :COUNT 32 {1002027B13}>)
  File "NIL", line NIL, in (FLET INS…
    ((FLET SB-IMPL::INSERT-AT :IN SB-IMPL::GET-PUTHASH-DEFINITIONS)
     #<unavailable argument> #<HASH-TABLE :TEST EQ :COUNT 32 {1002027B13}>
     #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100BD7FF13}> 129845308 T
     #<HASH-TABLE :TEST EQUAL :COUNT 0 {100C76F763}>)
  File "NIL", line NIL, in PUTHASH/E…
    (SB-IMPL::PUTHASH/EQ
     #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100BD7FF13}>
     #<unavailable argument> #<unavailable argument>)


Condition:   failed AVER: (= (HASH-TABLE-COUNT SB-IMPL::TABLE) SB-IMPL::HWM)
           This is probably a bug in SBCL itself. (Alternatively, SBCL might
           have been corrupted by bad user code, e.g. by an undefined Lisp
           operation like (FMAKUNBOUND 'COMPILE), or by stray pointers from
           alien code or from unsafe Lisp code; or there might be a bug in the
           OS or hardware that SBCL is running on.) If it seems to be a bug in
           SBCL itself, the maintainers would like to know about it. Bug
           reports are welcome on the SBCL mailing lists, which you can find at
           <http://sbcl.sourceforge.net/>.
```
